### ISSUE TITLE
Add training progress

### ISSUE THREAD

**Issue by ulziibuyan** [thesemicolonguy/neural-network-from-scratch#4]
During long waits of training and saving, I was getting confused if the program is stuck. Perhaps progress like the following would help? I can create separate PR or commit to #3 if you think its a good idea.

`Starting...`
`Training...`
`== EPOCH:  0 / 5  ==`
`Training with  60000 / 60000`
`Error:  9.15849543933`
`== EPOCH:  1 / 5  ==`
`Training with  23692 / 60000`
`...`
`Saving...`
`Testing...`
`Accurracy:  7.87`

**Comment by sar-gupta** [comment]
Sure, create another PR, I'll review and merge. @ulziibuyan
